def DadosRetornoCSV(TAMANHO_DADO, DADO_INICIO, DADO_FINAL, TEXTO_COMPLETO):
 DADOS_RESLTANTE = TEXTO_COMPLETO[DADO_INICIO + TAMANHO_DADO : DADO_FINAL-1]
 return DADOS_RESLTANTE.replace("\n", " ").strip()